
server:
  port: 8081

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:postgresql://localhost:5432/retail
    username: root
    password: 1
  jpa:
    generate-ddl: true

kafka:
  host: 10.24.32.11:9092